services:
  mysql-rp-inventory:
    image: mysql:latest
    container_name: mysql-rp-inventory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: RPInventoryDB
    ports:
      - "3316:3306"
    volumes:
      - ./deploy/inventory.init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_inventory_vol:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - retailpulse-network

  rp-inventory-app:
    image: rp-inventory-app:v0.1.0
    container_name: app-rp-inventory
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-rp-inventory:3306/RPInventoryDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: redis-rp-inventory
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: redis-password-inventory
      SERVER_PORT: 8084
      AUTH_SERVER_URL: http://app-iam:8081
    ports:
      - "8084:8084"
    depends_on:
      mysql-rp-inventory:
        condition: service_healthy
      # app-iam:
      #   condition: service_started
    networks:
      - retailpulse-network

  redis:
    image: redis:7.2
    container_name: redis-rp-inventory
    command: ["redis-server", "--requirepass", "redis-password-inventory"]
    restart: always
    ports:
      - "6379:6379"
    networks:
      - retailpulse-network

networks:
  retailpulse-network:
    driver: bridge

volumes:
  mysql_inventory_vol:

